[build]
  publish = "templates"

[[headers]]
  for = "/static/*"
  values = { cache-control = "public, max-age=31536000" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/static/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/static/js/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200